# Generated by debtap
# Maintainer: Will Furnass <w.furnass@sheffield.ac.uk>

pkgname=ronin-link-bin
_pkgname=ronin-link
pkgver=2.3.0
pkgrel=1
pkgdesc="A desktop app for linking to your machines securely in Ronin . A desktop app for linking to your machines securely in Ronin."
arch=('x86_64')
url="https://ronin.cloud"
license=('MIT')
groups=('')
depends=('alsa-lib' 'atk' 'at-spi2-atk' 'at-spi2-core' 'cairo' 'dbus' 'desktop-file-utils' 'discord' 'expat' 'gcc-libs' 'gdk-pixbuf2' 'glib2' 'glibc' 'gtk3' 'gvfs' 'hicolor-icon-theme' 'libcups' 'libnotify' 'libsecret' 'libx11' 'libxcb' 'libxcomposite' 'libxcursor' 'libxdamage' 'libxext' 'libxfixes' 'libxi' 'libxrandr' 'libxrender' 'libxss' 'libxtst' 'nspr' 'nss' 'pango' 'trash-cli' 'xdg-utils')
optdepends=('apparmor'
            'libgnome-keyring'
            'pulseaudio')
options=('!strip' '!emptydirs')
install=${pkgname}.install
source_x86_64=("https://ronin.cloud/apps/${_pkgname}-${pkgver}.deb")
sha512sums_x86_64=('ca386370e1a9eebfe4a0655e453a55ec62acf5bfbbbc326d71a722280bdafe4f83a7d8a6b9d21b65008ff9eb4dad66ea4bfb958fe8774db8c4ab46e0694dc3fd')

package(){

	# Extract package data
	tar -xI zstd -f data.tar.zst -C "${pkgdir}"

        install -D -m644 "${pkgdir}/usr/lib/${_pkgname}/LICENSES.chromium.html" "${pkgdir}/usr/share/licenses/${_pkgname}/LICENSE.html"
	install -D -m644 "${pkgdir}/usr/share/doc/${_pkgname}/copyright" "${pkgdir}/usr/share/licenses/${_pkgname}/COPYRIGHT"

}

# depends with no equiv in Arch:
#            'kde-cli-tools' 'kde-runtime' 
# optdepends with no equiv in Arch:
#            'gir1.2-gnomekeyring-1.0'
